name = "BuildkiteUtils"
uuid = "82f577da-a64f-4709-b926-88c56b51bf4b"
authors = ["Simon Byrne <simonbyrne@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[targets]
test = ["Test", "Plots"]
